I = imread("image.jpg");
X = I;
X(:,:,3) = zeros(size(I,1),size(I,2));
Y = I;
Y(:,:,2) = zeros(size(I,1),size(I,2));
Z = I;
Z(:,:,1) = zeros(size(I,1),size(I,2));
subplot(3,3,1);
imshow(X);
subplot(3,3,2);
imshow(Y);
subplot(3,3,3);
imshow(Z);
subplot(3,3,5);
imshow(I);
X1 = I;
X1(:,:,1) = zeros(size(I,1),size(I,2));
X1(:,:,2) = zeros(size(I,1),size(I,2));
Y1 = I;
Y1(:,:,1) = zeros(size(I,1),size(I,2));
Y1(:,:,3) = zeros(size(I,1),size(I,2));
Z1 = I;
Z1(:,:,2) = zeros(size(I,1),size(I,2));
Z1(:,:,3) = zeros(size(I,1),size(I,2));
subplot(3,3,7);
imshow(X1);
subplot(3,3,8);
imshow(Y1);
subplot(3,3,9);
imshow(Z1);